### ISSUE TITLE
ImageMagicとの依存性をなくす

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/SigDecontrastAviutl#1]
現在ImageMagicを用いて実装しているが、自前で実装する。

http://git.imagemagick.org/repos/ImageMagick/blob/95a0cd38fb4d4dd2725da85312268b7bd80bce10/MagickCore/enhance.c#L3683
以下最後までがIMでの実装のようである。

**Comment by MaverickTse** [comment]
That will be a completely new plugin, so making a new repo would be better.
IM's implementation is geared towards static image so that will be slow. Nevertheless, it serves as a reference on how the actual calculation is done.

**Comment by MaverickTse** [comment]
https://github.com/MaverickTse/SigContrastFastAviUtl/releases

Only contrast enhancement part is implemented at this moment. Just test things out... should be faster than the old plugin

**Comment by MaverickTse** [comment]
further discussion/work will be on the new repo as posted above. So closing this issue.
